plugins {
    id 'com.android.application'
}

android {
    namespace "me.hirameki.kotonoha"
    compileSdk 34

    defaultConfig {
        minSdk 28
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            cmake {
                arguments(
                        "-DCMAKE_TOOLCHAIN_FILE=/Users/nero/Codes/vcpkg/scripts/buildsystems/vcpkg.cmake",
                        "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/Users/nero/Library/Android/sdk/ndk/27.0.12077973/build/cmake/android.toolchain.cmake",
                        "-DCMAKE_SYSROOT=/Users/nero/Library/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/darwin-x86_64/sysroot",
                        "-DANDROID_STL=c++_shared"
                )
                // abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64' //Outros ABIs
                abiFilters 'arm64-v8a'
            }
        }
        targetSdk 33
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path '../../CMakeLists.txt'
        }
    }

    sourceSets.main {
        jniLibs.srcDir 'libs'
        assets.srcDir '../../assets'
    }

    lint {
        abortOnError false
    }
    buildFeatures {
        viewBinding true
    }
    ndkVersion '27.0.12077973'
    buildToolsVersion '37.0.0'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:2.0.4'
    implementation 'com.android.support:support-vector-drawable:28.0.0'
    implementation 'android.arch.lifecycle:livedata:1.1.1'
    implementation 'android.arch.lifecycle:viewmodel:1.1.1'
    implementation 'android.arch.navigation:navigation-fragment:1.0.0'
    implementation 'android.arch.navigation:navigation-ui:1.0.0'
    implementation 'com.android.support:design:28.0.0'
}
